version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: pokeset-backend
    ports:
      - "8080:8080"
    env_file:
      - ./Backend/.env
    networks:
      - pokeset-network

  frontend:
    build:
      context: ./Client/frontend
      dockerfile: Dockerfile
    container_name: pokeset-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - pokeset-network

networks:
  pokeset-network:
    driver: bridge
